{% set name = "earthnet" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/earthnet-{{ version }}.tar.gz
  sha256: badb5e464edcdf9a8a8266bd13169d8d1c9eb73f671b16e477aaf1f9603c26c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-image
    - tqdm
    - fire
    - pyproj
    - pandas
    - s3fs
    - xarray
    - netcdf4
    - matplotlib-base

test:
  imports:
    - earthnet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/earthnet
  summary: 'EarthNet2021 Toolkit: Download, Evaluation, Plotting'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
