{% set name = "earthnet" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/earthnet-{{ version }}.tar.gz
  sha256: 412fa87d461a50d6326b540bba59f72c71d9176017a16f288117ace9dcd759e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-image
    - tqdm
    - fire
    - pyproj
    - pandas
    - s3fs
    - xarray
    - netcdf4
    - matplotlib-base

test:
  imports:
    - earthnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/earthnet
  summary: 'EarthNet2021 Toolkit: Download, Evaluation, Plotting'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
